import Head from "next/head";
import Link from "next/link";
import styles from "./layout.module.css";

const siteName = "Nextjs_Blog"
export const siteTitle = "Nextjs Blog"

export default function Layout({ children, home }) {
  return (
    <div className={styles.container}>
      <Head>
        <title>{siteTitle}</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header className="header">
        <div className="header_inner flex justify-between items-center py-5">
          <Link href="/">
            <a className="cursor-pointer hover:opacity-70">
              <h1 className="text-2xl md:text-4xl">{siteName}</h1>
            </a>
          </Link>
          <nav>
            <ul className="flex justify-center items-center gap-3">
              <li>
                <Link href="/">
                  <a className="text-sm md:text-xl cursor-pointer hover:opacity-70">Top</a>
                </Link>
              </li>
              <li>
                <Link href="/quiita">
                  <a className="text-sm md:text-xl cursor-pointer hover:opacity-70">Quiita</a>
                </Link>
              </li>
              <li>
                <Link href="/contact">
                  <a className="text-sm md:text-xl cursor-pointer hover:opacity-70">Contact</a>
                </Link>
              </li>
            </ul>
          </nav>
        </div>
      </header>
      <main>
        {children}
      </main>
      {!home && (
        <div className="mt-7">
          <Link className="cursor-pointer" href="/">⬅️ ホームへ戻る</Link>
        </div>
      )}
    </div>
  );
};